---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# General information

Title of dataset: Arthropods in dead wood and soil

### Contact information:

Name: William Esbjug Gromstad

Institution: Norwegian University of Life Sciences

Email: [william.esbjug.gromstad\@nmbu.no](mailto:william.esbjug.gromstad@nmbu.no){.email}

### Contributors:

Eivind Kverme Ronold, Håvard Kauserud, Tone Birkemoe, Lisa Fagerli Lunde?

# Methodolical information

This study was performed on 12 sites positioned throughout southeastern Norway spanning 200 km in latitude and 160 km in longitude. Within each site we established two plots, with an average distance of 1270 m (range: 540-3140 m), where one was in a mature previously clear-cut stand and the other in a near-natural stand that had not been subjected to clear-cutting, but where selective cuttings (of various intensity) likely have occurred. 20 dead wood logs, all at least over 5 cm in diameter, were randomly selected along transects of in the 24 plots. Sawdust was collected from each log and six soil samples were pooled from each plot.

Samples were homogenized and DNA extracted using a modified CTAB protocol, then stored in -80°C. The COI gene using the primer pair BF3/BR2 (421 bp) from the DNA extracts. Illumina Miseq sequencing at StarSeq was used, and the sequences underwent bioinformatic sequencing as in <https://doi.org/10.1098/rspb.2021.2622>. Sequences were matched against the NCBI and BOLD databases.

# Data and file overview 
Lots of good info here 

# Data-specific information

